language: go
go_import_path: github.com/!!YOUR_HANDLE!!/picker
go:
  - 1.12
  - master

os:
  - linux
  - osx

dist: trusty
sudo: false
install: true

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test